# Generated by Django 4.2.7 on 2023-12-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_chatroommembership_remove_chatroom_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='pdf_file',
        ),
    ]
