# Generated by Django 4.2.7 on 2023-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_sickness_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickness',
            name='symptom',
            field=models.CharField(max_length=155),
        ),
    ]
