# Generated by Django 4.2.7 on 2023-11-30 05:15

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('policy', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhaar', models.CharField(editable=False, max_length=12, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('profile', models.ImageField(null=True, upload_to=core.models.profile_file_name)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('blood_group', models.CharField(max_length=5, null=True)),
                ('profession', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('insurance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.insurance')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
