# Generated by Django 4.2.7 on 2023-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar',
        ),
        migrations.AddField(
            model_name='user',
            name='aabhaId',
            field=models.CharField(default=None, editable=False, max_length=20, unique=True),
        ),
    ]
