# Generated by Django 4.2.7 on 2023-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_aadhaar_user_aabhaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aabhaId',
            field=models.CharField(default=None, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
